# Generated by Django 2.2.13 on 2021-02-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='desc',
            new_name='food_desc',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='name',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_name',
            field=models.CharField(default='FoodItem', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='poster',
            field=models.CharField(default='User', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='location',
            field=models.CharField(default='Address', max_length=50),
        ),
    ]
