# Generated by Django 2.2.13 on 2021-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210220_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='poster',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
