# Generated by Django 2.2.13 on 2021-02-21 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fooditem_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='time_available',
            new_name='time_available_start',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='time_available_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
