# Generated by Django 2.2.13 on 2021-02-21 08:24

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210221_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15, null=True), default=api.models.defaultValue, size=5),
        ),
    ]
